### PR TITLE
Added test for outlook encoding issue

### PR DESCRIPTION
**Pull request by DominikTo**
Rebased version of #215 to master.

### CODE REVIEW

**Comment by evert** [comment]
In the future, please just do a forced push in the original PR. This way we create a lot of extra issues and the context gets lost.

**Comment by evert** [comment]
Not really sure what to do with this ticket. At the moment we don't really change encodings for anything, we kind of keep everything as-is, including this. It would make sense to convert everything to UTF-8 during the parsing phase, but that's a larger task. Vobject4 would be the right time to do that though.

**Comment by DominikTo** [comment]
Oh, is there a way to change the target branch in the meantime? I thought that's still not possible to change from e.g. "3.4" to "master".

**Comment by DominikTo** [comment]
#41 and #43 might be related to this one.

**Comment by evert** [comment]
I just took a look at this branch and updated it with master. I think it would be good to get a true original that demonstrates the issue. `QUOTED-PRINTABLE` no longer exists in vCard 3.0, so I find it a bit suspicious that it appears here. Is it possible that it was actually a vCard 2.1 object?

**Comment by DominikTo** [comment]
The original card didn't contain a PRODID, so it's unfortunately unknown what created this.

**Comment by evert** [comment]
Maybe it's not worth fixing then. I think we need some sort of reputable source / repeatable issue to really make it worth our while. I will close this ticket, and if we come across a popular application that produces something like this, we can always reconsider.

**Pull request closed without merging**
