### PR TITLE
Add Pacific Time (US & Canada) as exchange timezone

### PR DESCRIPTION
**Pull request by laoneo**
As the tilt says, it adds _Pacific Time (US & Canada)_ as exchange timezone.

### CODE REVIEW

**Comment by evert** [comment]
Can you share a sample file for this? This string is not on the official list.

**Comment by laoneo** [comment]
A user of my Joomla extension reported the time shift when using office365. Here is a trimmed down ical file:

```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Academic Calendar Summer
BEGIN:VTIMEZONE
TZID:(UTC-08:00) Pacific Time (US & Canada)
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:This is a test event.\n
UID:040000008200E0007444A7
SUMMARY:Test. should show 12:00 PM - 12:30 PM
DTSTART;TZID="(UTC-08:00) Pacific Time (US & Canada)":20170525T120000
DTEND;TZID="(UTC-08:00) Pacific Time (US & Canada)":20170525T123000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20170522T060220Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:OCCI\, 1988 Newmark AVE\, Coos Bay\, OR
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
```

**Comment by evert** [comment]
I worry that it might simply be some other software that's generating this (or mangling this after exchange generated this). Most microsoft products will include other properties in `VTIMEZONE` that appear to be missing here. In particular I would expect a `X-MICROSOFT-CDO-TZID` property here. If it was there, the timezone would have been picked up correctly.

Basically, I would say:

* Find out if this is a reproducable issue with a real microsoft product.
* If not, try to fix the bug in the software that generated this.

A more permanent fix for situations like this is #248, which should pretty much cover all edge-cases.

**Comment by laoneo** [comment]
Thanks for the information. The link I'm getting this ics content from is directly from https://outlook.office365.com/owa/calendar/blablabla, so there is no software in between.

I saw that open issue already, but it looks like it will take a huge effort to implement which I think nobody will do in the closer future.

**Comment by evert** [comment]
Alright, I believe it. It's a bit frutrating that there's no official source for these strings, but what can you do.

**Comment by laoneo** [comment]
I absolutely understand your frustration. Gladly Github has this thingy called "pull requests". Thanks for the merge.

**Pull request merged**
