### PR TITLE
Invitee change status in first event of a recurring events.

### PR DESCRIPTION
**Pull request by vkomrakov-sugar**

### CODE REVIEW

**Comment by evert** [comment]
Thanks for re-doing this PR.

**Comment by evert** [comment]
So I am not fully convinced that your proposed change is a correct one. I'm going to rewrite your tests to be in the format of the rest of the iTip tests and figure out from where what the expected behavior is.

**Comment by evert** [comment]
Alright, I had a bit of a deeper dive into the issue. I see a problem. Here's your original event (simplified)

```
BEGIN:VEVENT
DTSTART:20160321T170000Z
ATTENDEE;CN=User Test1;PARTSTAT=NEEDS-ACTION:mailto:invitee@company.name
ORGANIZER;CN=User Test2:mailto:organizer@company.name
ATTENDEE;PARTSTAT=ACCEPTED;CN=User Test2;ROLE=CHAIR:mailto:organizer@company.name
RRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20160323T235959Z
END:VEVENT
```

Then that event gets updated by the invitee. This is the new version (also simplified)

```
BEGIN:VEVENT
ATTENDEE;CN=User Test1;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION:mailto:invitee@company.name
ATTENDEE;CN=User Test2;CUTYPE=INDIVIDUAL;PARTSTAT=ACCEPTED;ROLE=CHAIR:mailto:organizer@company.name
ORGANIZER;CN=User Test2:mailto:organizer@company.name
DTSTART:20160321T170000Z
RRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20160323T235959Z
END:VEVENT
BEGIN:VEVENT
ATTENDEE;CN=User Test1;CUTYPE=INDIVIDUAL;PARTSTAT=ACCEPTED:mailto:invitee@company.name
ATTENDEE;CN=User Test2;CUTYPE=INDIVIDUAL;PARTSTAT=ACCEPTED;ROLE=CHAIR:mailto:organizer@company.name
SUMMARY:test
DTSTART:20160321T170000Z
ORGANIZER;CN=User Test2:mailto:organizer@company.name
RECURRENCE-ID:20160321T170000Z
END:VEVENT
END:VCALENDAR
```

What we see here is that the updated version contains the master event twice: once as the original master event, and once as an override.

I honestly did not know that was allowed in iCalendar. I thought that it never makes sense to override the master event. I see now though it sometimes makes sense.

I need to figure out if this is valid iCalendar. If it is, I suspect that there's deeper problems that need to be solved first.

**Comment by evert** [comment]
I posted a question on the iCalendar list to help me out here. Based on their answer I feel confident I can solve fix my implementation.

**Comment by Michael-Gusev** [comment]
@evert, it's not duplicate of master event, it's change in the 1st accurence, not in all series.
I described case in the issue: https://github.com/fruux/sabre-vobject/issues/306

**Pull request closed without merging**
