### PR TITLE
incorrect work with timezone without event master

### PR DESCRIPTION
**Pull request by vkomrakov-sugar**

### CODE REVIEW

**Comment by Michael-Gusev** [comment]
@evert could you review?
Problem here that `$recurId` has different values / format in different places:
in `processMessageReply` method it's `YmdTHisZ` but in `$existingObject->VEVENT` так `YmdTHis`.

**Comment by evert** [comment]
The problem with this proposed fix is that it assumes that the first `VTIMEZONE` holds the correct info, which might very well be incorrect. I'm looking a bit further into this to see if there's another fix possible.

Thanks for the complete unittest though. Very awesome.

**Comment by Michael-Gusev** [comment]
Thank you, @evert. Could you tell us next release date?

**Comment by evert** [comment]
Yesterday!

**Comment by Michael-Gusev** [comment]
Ahahaha :+1:

**Comment by Michael-Gusev** [comment]
Hi @evert, one more thing. We can't use 5.5 and use 5.4 but I found fix was released under 4.1.0, and we need it under 3.5.x.
Could you add it to 3.5.x release?
Thank you.

**Comment by Michael-Gusev** [comment]
@evert, could you check my prev comment?

**Comment by evert** [comment]
I just backported it to the 3.5 branch.

**Pull request merged**
